version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=zKwP7byWWQktPdRjpgANt9lN1kliTsAH
      - DATABASE_URL=mongodb://mongodb:27017/bookshop
      - FRONTEND_URL=http://frontend:5173/
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
